version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: SEA_container
    expose:
      - "8001"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./static:/static
    environment:
      - PYTHONUNBUFFERED=1
      - LOCAL_DEV=1
      - PQA_HOME=/app/data
      - PAPER_DIRECTORY=/app/data/papers
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8001
    depends_on:
      - redis
  
  frontend:
      image: python:3.11-alpine
      ports:
        - "8000:8000"  # Changed from expose to ports for direct access if needed
      volumes:
        - ./frontend:/app/frontend:delegated  # Added delegated for better performance
      working_dir: /app/frontend
      command: python -m http.server 8000
      environment:
        - PYTHONUNBUFFERED=1
      depends_on:
        - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/app/frontend:ro,delegated  # Added delegated for better performance
      - ./static:/static:ro  # <--- add this so Nginx sees the same folder
    depends_on:
      - web
      - frontend
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
