version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: SEA_container
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - persistent_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOCAL_DEV=0
      - PQA_HOME=/app/data
      - PAPER_DIRECTORY=/app/data/papers
    command: uvicorn app:app --host 0.0.0.0 --port 8001
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  persistent_data:
  redis_data:
